Do not update keys
Temporarily disable keys update because of the following error:

ERROR: A specified local key could not be updated from a keyserver.

Our base container was updated today so we shouldn't have problems.